#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o noglob -o nounset -o pipefail

make -B -C ./nvim/all/telescope-fzf-native.nvim/
(cd ./nvim/all/parinfer-rust && cargo build --release)
make -B -C ./nvim/all/LuaSnip/ install_jsregexp
make -C zsh/ble.sh

nvim --headless +'helptags ALL' +qa
#%MAINT::
# :helptags ALL
# :TSUpdate


# HACK: ignore generated :/doc/tags in each submodule state
# FAIL: hardcoded /bin/sh on ubuntu resolves to !dash,
#   and we can't use "bash -c" COS vars $toplevel and $name become empty
git submodule --quiet foreach '
  f=$toplevel/.git/modules/$name/info/exclude;
  fign(){ if ! grep -qxF "$1" "$f"; then echo "$1" >> "$f"; echo "[$f] $1"; fi; };
  for x in doc/tags lisp/system-index.txt; do [[ -f $x ]] && fign "/$x"; done;
  [[ ${name%%/*} == zsh ]] && fign "/*.zwc";
  true
'
