#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o noglob -o nounset -o pipefail

nvim --headless +'helptags ALL' +qa
#%MAINT:: (after all plugins are lazy-loaded)
# :helptags ALL
# :TSUpdate

# HACK: ignore generated :/doc/tags in each submodule state
# FAIL: hardcoded /bin/sh on ubuntu resolves to !dash,
#   and we can't use "bash -c" COS vars $toplevel and $name become empty
git submodule --quiet foreach '
  f=$toplevel/.git/modules/$name/info/exclude;
  fign(){ if ! grep -qxF "$1" "$f"; then echo "$1" >> "$f"; echo "[$f] $1"; fi; };
  for x in doc/tags lisp/system-index.txt; do [ -f "$x" ] && fign "/$x"; done;
  [ "${name%%/*}" = zsh ] && fign "/*.zwc";
  true
'

make -B -C ./nvim/all/telescope-fzf-native.nvim/
(cd ./nvim/all/parinfer-rust && cargo build --release)
make -B -C ./nvim/all/LuaSnip/ install_jsregexp
make -C zsh/ble.sh

## FAIL: no reliable way to exit after any error, "-cqa" is triggered before lazy,
#   and LazyPluginsLoaded isn't triggered at all if error occurs
#   ALT: some hard trigger -c "lua vim.defer_fn(function() pcall(vim.cmd, 'qa!') end, 3000)"
# WKRND: will exit if all is fine, but will freeze on error, so <C-c> it
# ALT:BAD:(not all actions done): env -C ./nvim/all/blink.cmp/ -- cargo build --release
# ALT:BAD:(monstrosity): /d/airy/nvim/lua/plug/#/blinkcmp_build.lua
env -C ./nvim/all/blink.cmp/ BLINKCMP_REBUILD=1 nvim --headless \
  -c "autocmd User LazyPluginsLoaded ++once lua vim.cmd('qa')" 2>&1


zsh -euc '
  # set -eu -x
  cd ./zsh/fzf-tab
  source ./fzf-tab.plugin.zsh
  build-fzf-tab-module
'

zsh -euc '
  setopt extendedglob
  srcs=( /d/{airy,plugins}/zsh/**/*.zsh~*/[#_]*/*(N) )
  autoload -Uz zrecompile
  for f in $srcs; do zrecompile -p $f --; done

  _compdump="${ZDOTDIR:-$HOME}/.zcompdump"
  rm -f "$_compdump"
  autoload -Uz compinit
  compinit -d "$_compdump"
  zrecompile -p ${ZDOTDIR:-$HOME}/.zshrc --
  zrecompile -p "$_compdump" --
'

echo "DONE"
