#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o noglob -o nounset -o pipefail
git submodule update --init --remote --jobs=5 --recursive --single-branch --depth=1 --recommend-shallow --
